# Generated by Django 4.2.2 on 2023-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='cons',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='decision',
            name='pros',
            field=models.JSONField(default=list),
        ),
    ]
