# Generated by Django 4.2.2 on 2023-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0002_alter_decision_cons_alter_decision_pros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='cons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='pros',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
